name: Build  Rootfs

on: 
  workflow_dispatch:

 
jobs:
  build-rootfs:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Create Ubuntu Rootfs
        run: |
          bash build.sh
          upload=$(realpath rootfs.tar.gz)
          echo "FILE1=$upload" >> $GITHUB_ENV
          echo "codename=$(cat codename)" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ubuntu-${{ env.codename }}
          name: "Release ubuntu"
          body: "This release includes the latest build for Ubuntu  ${{ env.VERSION }} rootfs."
          files: |
                ${{ env.FILE1 }}
            
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
