name: Build Debian Rootfs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-rootfs:
    runs-on: ubuntu-latest

    steps:
      - name: Set up the environment
        run: |
          sudo apt-get update
          sudo apt-get install -y debootstrap

      - name: Create Debian Rootfs
        run: |
          # Define the rootfs output directory with full path
          export ROOTFS_DIR="${{ github.workspace }}/debian-rootfs"
          
          # Make sure the directory is created and empty
          sudo rm -rf "$ROOTFS_DIR"
          sudo mkdir -p "$ROOTFS_DIR"
          
          # Run debootstrap with minbase variant
          sudo debootstrap --variant=minbase --arch=amd64 stable "$ROOTFS_DIR" http://deb.debian.org/debian

      - name: Verify Rootfs Directory
        run: |
          # Check if the rootfs directory exists and is populated
          if [ -d "${{ github.workspace }}/debian-rootfs" ] && [ "$(ls -A "${{ github.workspace }}/debian-rootfs")" ]; then
            echo "Rootfs directory is populated."
          else
            echo "Rootfs directory is empty or does not exist. Exiting."
            exit 1
          fi

      - name: Archive rootfs
        run: |
          # Compress the rootfs into a tarball
          sudo tar -czf "${{ github.workspace }}/debian-rootfs.tar.gz" -C "${{ github.workspace }}/debian-rootfs" .
          sudo chown $USER:$USER "$OUTPUT_TARBALL"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0  # Set your desired version/tag here
          release_name: "Debian Rootfs Release v1.0.0"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload rootfs to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/debian-rootfs.tar.gz
          asset_name: debian-rootfs.tar.gz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
