name: Build Debian Rootfs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-rootfs:
    runs-on: ubuntu-latest

    steps:
      - name: Set up the environment
        run: |
          sudo apt-get update
          sudo apt-get install -y debootstrap

      - name: Create Debian Rootfs Tarball
        run: |
          
          # Use debootstrap to create a minbase Debian rootfs tarball directly
          sudo debootstrap --variant=minbase --arch=amd64 --make-tarball=root stable  http://deb.debian.org/debian
          
          # Adjust ownership to ensure the GitHub Actions runner user owns the tarball
          sudo chown $USER:$USER root.tar

      - name: Upload rootfs artifact
        uses: actions/upload-artifact@v3
        with:
          name: debian-rootfs
          path: root.tar
