name: Build Debian Rootfs
#rr
on:
  workflow_dispatch:

jobs:
  build-rootfs:
    runs-on: ubuntu-latest

    steps:
      - name: Set up the environment
        run: |
          sudo apt-get update
          sudo apt-get install -y debootstrap
          export ROOTFS_DIR="${{ github.workspace }}/debian-rootfs"
          sudo debootstrap --variant=minbase --arch=amd64 stable "$ROOTFS_DIR" http://deb.debian.org/debian
          sudo rm -rf $ROOTFS_DIR/var/cache/apt/
          sudo tar -czf "${{ github.workspace }}/debian-rootfs.tar.gz" -C "${{ github.workspace }}/debian-rootfs" .

      - name: Create a new GitHub release and tag
        uses: softprops/action-gh-release@v2
        with:
          tag_name: debian
          name: "Release debian"
          body: "This release includes the latest build for Debian rootfs :-"
          files: |
            ${{ github.workspace }}/debian-rootfs.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
