name: Build Debian Rootfs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-rootfs:
    runs-on: ubuntu-latest

    steps:
      - name: Set up the environment
        run: |
          sudo apt-get update
          sudo apt-get install -y debootstrap

      - name: Create Debian Rootfs Tarball
        run: |
          # Define the output tarball path
          OUTPUT_TARBALL="${{ github.workspace }}/debian-rootfs.tar.gz"
          
          # Use debootstrap to create a minbase Debian rootfs tarball directly
          sudo debootstrap --variant=minbase --arch=amd64 --make-tarball="$OUTPUT_TARBALL" stable "" http://deb.debian.org/debian
          
          # Adjust ownership to ensure the GitHub Actions runner user owns the tarball
          sudo chown $USER:$USER "$OUTPUT_TARBALL"

      - name: Upload rootfs artifact
        uses: actions/upload-artifact@v3
        with:
          name: debian-rootfs
          path: ${{ github.workspace }}/debian-rootfs.tar.gz
