name: Create Tag

on:
  workflow_run:
    workflows: ["Build Debian Rootfs"]  # Ensure this matches the name of the first workflow
    types:
      - completed

jobs:
  tag:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Tag
        run: |
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')"  # Example tag format based on date/time
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Notify about the new tag
        run: echo "New tag $TAG_NAME created and pushed."
