name: Build Ubuntu Rootfs

on: workflow_dispatch

jobs:
  build-rootfs:
    runs-on: ubuntu-latest

    steps:
      - name: Create Ubuntu Rootfs
        run: |
          sudo bash build.sh
          upload=$(realpath rootfs.tar.gz)
          echo "VERSION=$(cat version)" >> $GITHUB_ENV
          echo "FILE1=$upload" >> $GITHUB_ENV

      - name: Create a new GitHub release and tag
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: "Release ${{ env.VERSION }}"
          body: "This release includes the latest build for Ubuntu  ${{ env.VERSION }} rootfs."
          files: |
                ${{ env.FILE1 }}
            
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
